import React, { useEffect, useState } from 'react';
import { BACKEND_BASE_URL } from '@/config/api';

export default function QPUpload() {
  const [file, setFile] = useState<File | null>(null);
  const [scanning, setScanning] = useState(false);
  const [questions, setQuestions] = useState<any[]>([]);
  const [titles, setTitles] = useState<Array<{id:number,title:string}>>([]);
  const [selectedTitle, setSelectedTitle] = useState<number | null>(null);
  const [importing, setImporting] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    fetch(`${BACKEND_BASE_URL}/api/question-bank-titles`)
      .then(r => r.ok ? r.json() : [])
      .then(data => setTitles(data || []))
      .catch(() => setTitles([]));
  }, []);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0] || null;
    setFile(f);
    setQuestions([]);
    setMessage(null);
  };

  const uploadAndScan = async () => {
    if (!file) return setMessage('Please choose a .docx file');
    setScanning(true);
    setMessage(null);
    try {
      const fd = new FormData();
      fd.append('file', file, file.name);
      const res = await fetch(`${BACKEND_BASE_URL}/api/template/scan-docx`, {
        method: 'POST', body: fd
      });
      if (!res.ok) {
        const text = await res.text();
        throw new Error(`Scan failed: ${res.status} ${text}`);
      }
      const data = await res.json();
      setQuestions(data.questions || []);
      setMessage(`Parsed ${ (data.questions||[]).length } question(s)`);
    } catch (err: any) {
      console.error(err);
      setMessage(err?.message || String(err));
    } finally {
      setScanning(false);
    }
  };

  const importToBank = async () => {
    if (!questions.length) return setMessage('No parsed questions to import');
    if (!selectedTitle) return setMessage('Choose a target Question Bank title');
    setImporting(true);
    setMessage(null);
    try {
      // Map scanned question fields to question_bank schema
      const payload = questions.map(q => {
        const opts = q.options && Array.isArray(q.options) && q.options.length ? q.options : null;
        return {
          question_text: q.text || q.question || q.question_text || '',
          type: opts ? 'objective' : (q.type || 'descriptive'),
          options: opts,
          images: q.images || null,
          correct_answer: q.correct_answer || null,
          answer_text: q.answer_text || null,
          btl: Number(q.btl) || 2,
          marks: Number(q.marks) || 2,
          chapter: q.chapter || null,
          course_outcomes: q.co || q.course_outcomes || null
        };
      });
      const fd = new FormData();
      fd.append('title_id', String(selectedTitle));
      fd.append('status', 'pending');
      fd.append('payload', JSON.stringify(payload));

      const res = await fetch(`${BACKEND_BASE_URL}/api/question-bank/bulk`, { method: 'POST', body: fd });
      if (!res.ok) {
        const text = await res.text();
        throw new Error(`Import failed: ${res.status} ${text}`);
      }
      const json = await res.json();
      setMessage(`Imported ${json.inserted || 0} questions`);
      setQuestions([]);
    } catch (err: any) {
      console.error(err);
      setMessage(err?.message || String(err));
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="container mx-auto p-6">
      <h1 className="text-2xl font-bold mb-4">QP Upload - Scan DOCX</h1>
      <p className="text-sm text-muted-foreground mb-4">Upload a Word (.docx) generated by the template generator. This page will scan the document and extract questions which you can import into the Question Bank.</p>

      <div className="mb-4">
        <input type="file" accept=".docx" onChange={handleFileChange} />
        <button className="ml-3 btn btn-primary" onClick={uploadAndScan} disabled={scanning || !file}>{scanning ? 'Scanning...' : 'Scan DOCX'}</button>
      </div>

      {message && <div className="mb-4 text-sm text-red-600">{message}</div>}

      {questions.length > 0 && (
        <div>
          <div className="mb-3">
            <label className="block font-medium">Target Question Bank Title</label>
            <select value={selectedTitle || ''} onChange={e => setSelectedTitle(Number(e.target.value) || null)} className="mt-1">
              <option value="">-- choose title --</option>
              {titles.map(t => <option key={t.id} value={t.id}>{t.title}</option>)}
            </select>
            <button className="ml-3 btn btn-secondary" onClick={importToBank} disabled={importing}>{importing ? 'Importing...' : 'Import to Question Bank'}</button>
          </div>

          <div className="overflow-auto max-h-96 border rounded p-2">
            <ol className="list-decimal pl-6 space-y-3">
              {questions.map((q, i) => (
                <li key={i} className="mb-2">
                  <div className="font-semibold">{q.number || q.num || i+1}. {q.text || q.question || q.question_text}</div>
                  <div className="text-sm text-muted">CO: {q.co || '-'} &nbsp; BTL: {q.btl || '-'} &nbsp; Marks: {q.marks || '-'}</div>
                  {q.images && Array.isArray(q.images) && q.images.length > 0 && (
                    <div className="mt-2 space-x-2">
                      {q.images.map((src: string, idx: number) => (
                        <img key={idx} src={src} alt={`question-${i}-img-${idx}`} className="inline-block max-w-full max-h-40 border" />
                      ))}
                    </div>
                  )}
                </li>
              ))}
            </ol>
          </div>
        </div>
      )}
    </div>
  );
}
